apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: desafio3

data:
  DB_PORT: "5432"

  DB_AUTH_NAME: "authdb"
  DB_FLAG_NAME: "flagdb"
  DB_TARGET_NAME: "targetingdb"

  DB_AUTH_HOST: "togglemaster-auth.cimepsxaa4ta.us-east-1.rds.amazonaws.com"
  DB_FLAG_HOST: "togglemaster-flag.cimepsxaa4ta.us-east-1.rds.amazonaws.com"
  DB_TARGET_HOST: "togglemaster-targeting.cimepsxaa4ta.us-east-1.rds.amazonaws.com"

  REDIS_HOST: "togglemaster-redis.e6uhnk.0001.use1.cache.amazonaws.com"
  REDIS_PORT: "6379"

  AUTH_SERVICE_URL: "http://auth-service-svc.desafio3.svc.cluster.local:8080"
  FLAG_SERVICE_URL: "http://flag-service-svc.desafio3.svc.cluster.local:8080"
  TARGETING_SERVICE_URL: "http://targeting-service-svc.desafio3.svc.cluster.local:8080"

  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/596081564794/togglemaster-sqs"

  PORT: "8080"
  APP_PORT: "8080"

  AWS_REGION: "us-east-1"