apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: desafio3

type: Opaque

stringData:
  DB_AUTH_USER: "admin_auth"
  DB_FLAG_USER: "admin_flag"
  DB_TARGET_USER: "admin_targeting"

  DB_AUTH_PASSWORD: "SenhaSegura123!"
  DB_FLAG_PASSWORD: "SenhaSegura123!"
  DB_TARGET_PASSWORD: "SenhaSegura123!"

  MASTER_KEY: "admin-secreto-123"

  SERVICE_API_KEY: "tm_key_c74992329539932b41556cbe33fd2bf1af2804fc61d09b8b64ea7bd775fc2d55"
