apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-sa
  namespace: desafio3

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service-sa
  namespace: desafio3
