name: Auth Service CI

on:
  push:
    branches:
      - main
    paths:
      - "auth-service/**"
      - "terraform/**"
      - ".github/workflows/auth-service-ci.yml"

  pull_request:
    branches:
      - main
    paths:
      - "auth-service/**"
      - "terraform/**"
      - ".github/workflows/auth-service-ci.yml"

env:
  AWS_REGION: us-east-1

jobs:
  # =========================================================
  # 1 - BUILD & UNIT TEST
  # =========================================================
  build-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: auth-service/go.mod
          cache-dependency-path: auth-service/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Unit Tests
        run: go test ./...

  # =========================================================
  # 2 - LINTER / STATIC ANALYSIS
  # =========================================================
  lint:
    name: Linter & Static Analysis
    runs-on: ubuntu-latest
    needs: build-test

    defaults:
      run:
        working-directory: auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: auth-service/go.mod
          cache-dependency-path: auth-service/go.sum

      - name: Go Vet
        run: go vet ./...

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.13
          working-directory: auth-service

  # =========================================================
  # 3 - SECURITY SCAN
  # =========================================================
  security:
    name: Security Scan - SAST & SCA
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gosec SAST
        uses: securego/gosec@master
        with:
          args: ./auth-service/...

      - name: Trivy SCA
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: auth-service
          severity: CRITICAL
          exit-code: "1"

  # =========================================================
  # 4 - DOCKER BUILD, SCAN & PUSHh
  # =========================================================
  docker:
    name: Docker Build, Scan & Push
    runs-on: ubuntu-latest
    needs: security

    permissions:
      contents: read

    outputs:
      ecr_url: ${{ steps.terraform-output.outputs.ecr_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build
        working-directory: auth-service
        run: |
          docker build \
            --tag togglemaster-auth-service:${{ github.sha }} \
            .

      - name: Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: togglemaster-auth-service:${{ github.sha }}
          severity: CRITICAL
          exit-code: "1"
      - name: Configure AWS Credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: terraform
        run: terraform init -input=false

      - name: Read Auth ECR URL
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: terraform-output
        working-directory: terraform
        shell: bash
        run: |
          ECR_URL=$(terraform output -json ecr_repository_urls | jq -r '."auth"')

          if [ -z "${ECR_URL}" ] || [ "${ECR_URL}" = "null" ]; then
            echo "URL do auth-service não encontrada nos outputs."
            exit 1
          fi

          echo "ECR URL encontrada: ${ECR_URL}"
          echo "ecr_url=${ECR_URL}" >> "$GITHUB_OUTPUT"

      - name: Login to Amazon ECR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          ECR_URL: ${{ steps.terraform-output.outputs.ecr_url }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag \
            togglemaster-auth-service:${IMAGE_TAG} \
            "${ECR_URL}:${IMAGE_TAG}"

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          ECR_URL: ${{ steps.terraform-output.outputs.ecr_url }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push "${ECR_URL}:${IMAGE_TAG}"

  # =========================================================
  # 5 - UPDATE GITOPSs
  # =========================================================
  gitops:
    name: Update GitOps
    runs-on: ubuntu-latest
    needs: docker

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Auth Service Image
        env:
          ECR_URL: ${{ needs.docker.outputs.ecr_url }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE="${ECR_URL}:${IMAGE_TAG}"

          echo "Nova imagem:"
          echo "${IMAGE}"

          python - <<'PY'
          import os
          import yaml

          file_path = "k8s/03-apps-deployments.yaml"

          image = os.environ["ECR_URL"] + ":" + os.environ["IMAGE_TAG"]

          with open(file_path, "r") as file:
              documents = list(yaml.safe_load_all(file))

          found = False

          for document in documents:
              if not document:
                  continue

              if (
                  document.get("kind") == "Deployment"
                  and document.get("metadata", {}).get("name") == "auth-service"
              ):
                  containers = (
                      document
                      .get("spec", {})
                      .get("template", {})
                      .get("spec", {})
                      .get("containers", [])
                  )

                  for container in containers:
                      if container.get("name") == "auth-service":
                          container["image"] = image
                          found = True

          if not found:
              raise Exception(
                  "Deployment/container auth-service não encontrado."
              )

          with open(file_path, "w") as file:
              yaml.safe_dump_all(
                  documents,
                  file,
                  sort_keys=False
              )

          print(f"Imagem atualizada para: {image}")
          PY

      - name: Show GitOps Changes
        run: git diff

      - name: Commit GitOps Change
        env:
          IMAGE_TAG: ${{ github.sha }}
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add k8s/03-apps-deployments.yaml

          if git diff --cached --quiet; then
            echo "Nenhuma alteração necessária."
            exit 0
          fi

          git commit \
          -m "chore(gitops): update auth-service image to ${IMAGE_TAG}"

          echo "Atualizando branch local..."

          git fetch origin main
          git rebase origin/main

          echo "Enviando alteração GitOps..."

          git push origin HEAD:main
